name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          
          git checkout --orphan temp-deploy-branch
          
          rm -f frontend/src/assets/dashboard-preview.png || true
          
          git add -A
          git commit -m "deploy: clean production sync"
          
          git push --force https://Mnsory:$HF_TOKEN@huggingface.co/spaces/Mnsory/PharmaCore temp-deploy-branch:main
